version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "9003:9003" # Mapeie a porta do Xdebug
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DATABASE: apivendas
      MYSQL_ROOT_PASSWORD: apivendas2024
      MYSQL_USER: apivendas
      MYSQL_PASSWORD: password
      QUEUE_CONNECTION: redis # Alteração aqui para usar o Redis

    depends_on:
      - db
      - redis # Adicione o serviço Redis
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: apivendas
      MYSQL_ROOT_PASSWORD: apivendas2024
      MYSQL_USER: apivendas
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:alpine # Imagem oficial do Redis

volumes:
  db_data:
